version: '3.1'
services:
  db:
    image: mysql
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 1234567
    ports:
      - "3306:3306"
    volumes:
      - cdc:/var/lib/mysql

volumes:
  cdc: